# the type of dynamic content
type: "shotgun_step"

# the shotgun field to use for the folder name
name: "short_name"

#filters:
#     - { "path": "short_name", "relation": "in", "values": [ "PST", "PST"] }
